# 6. 🎨 Visualization Ideas (using matplotlib or seaborn)
 
# Plot a histogram of Age ✅ 
# Draw a bar chart of survival count ✅ 
# Create a box plot of Fare by Sex ✅ 
# Make a scatterplot of Age vs Fare ✅ 
# Plot Survival rate by Gender using seaborn ✅ 

