# 4. 📈 Sorting and Aggregating

# Sort passengers by Age descending ✅ 
# Sort by Fare, highest to lowest ✅ 
# Find the average Age of all passengers ✅ 
# Find the average Fare paid by survivors ✅ 
# Group by Sex and find mean Fare for each gender ✅ 
# Group by Survived and count how many in each group ✅ 

