# 1. 🔁 Step Into

# 1. Display first few rows ✅
import pandas

# 2. Get basic info ✅
# 3. Summary statistics ✅
# 4. Check column names ✅
# 5. List all female passengers ✅
# 6. List all passengers who survived ✅
# 7. Get average age of all passengers ✅
# 8. Get median fare paid ✅
# 9. Sort passengers by Fare (descending) ✅
# 10. Plot Age vs Fare (Optional, if using matplotlib/seaborn) ✅

