# 3. 📊 Filtering and Selection

# Show all passengers aged over 30 ✅ 
# Show all female survivors ✅ 
# Show all passengers who paid more than 20 ✅ 
# Show all males who didn’t survive ✅ 
# Show all passengers with Fare between 10 and 50 ✅ 


