# 2. 📌 Basic Exploration

# Show the number of passengers ✅
# List all column names ✅ 
# Display data types of each column ✅ 
# Count how many males vs females there are ✅ 
# Count how many passengers survived vs died ✅ 