# 7. 🔁 Bonus Logic Tasks

# Create a new column: IsChild → True if Age < 18 ✅ 
# Create a new column: FareCategory → 'Low', 'Mid', 'High' based on Fare value ✅ 
# Find the youngest and oldest passengers ✅ 
# Find the passenger(s) who paid the most ✅ 