# 5. 🔥 Data Cleaning Practice

# Check for missing values ✅ 
# Fill missing Age with average Age ✅ 
# Drop passengers with missing Fare (if any) ✅ 
# Convert Sex column to numeric (0 = male, 1 = female) ✅ 
